'use client'

/**
 * ReportActions — interactive action bar shown beneath the Control Room
 * Reports table. Operates on the *currently visible* (filter + search
 * filtered) report set so users can Copy to clipboard, Share, Export (CSV),
 * and Print exactly what they are looking at.
 *
 * AGENT-TRACE: Built on the canonical @repo/ui `Button` + `sonner` toast to
 * match every other interactive surface in this view. Clipboard / Web Share
 * APIs are guarded with fallbacks because jsdom and older browsers may not
 * implement `navigator.clipboard` / `navigator.share`.
 */

import { useState, useCallback } from 'react'
import { Button } from '@repo/ui/components/ui/button'
import { toast } from 'sonner'
import { Copy, Share2, Download, Printer, Check, Loader2 } from 'lucide-react'

interface GeneratedReportRow {
  id: string
  generated_at: string
  pdf_url: string | null
  report_date: string
  shift_type: string | null
  report_data: Record<string, string | number | boolean | null | undefined>
  creator: { full_name: string } | { full_name: string }[] | null
  template: { name: string } | { name: string }[] | null
}

interface ReportActionsProps {
  reports: GeneratedReportRow[]
}

function resolveTemplateName(template: { name: string } | { name: string }[] | null): string {
  if (Array.isArray(template)) return template[0]?.name || 'Operations Summary Report'
  return template?.name || 'Operations Summary Report'
}

function resolveCreatorName(
  creator: { full_name: string } | { full_name: string }[] | null
): string {
  if (Array.isArray(creator)) return creator[0]?.full_name || 'System Auto-Compile'
  return creator?.full_name || 'System Auto-Compile'
}

function summarizeData(data: Record<string, string | number | boolean | null | undefined>): string {
  if (!data || typeof data !== 'object') return ''
  const parts: string[] = []
  if (data.total_tonnage) parts.push(`Tonnage: ${data.total_tonnage}t`)
  if (data.tonnes) parts.push(`Tonnage: ${data.tonnes}t`)
  if (data.loads) parts.push(`Loads: ${data.loads}`)
  if (data.active_machines) parts.push(`Machines: ${data.active_machines}`)
  if (data.delays_count !== undefined) parts.push(`Delays: ${data.delays_count}`)
  if (parts.length === 0) {
    Object.keys(data)
      .slice(0, 3)
      .forEach((key) => {
        const val = data[key]
        if (typeof val === 'number' || typeof val === 'string') {
          parts.push(`${key.replace(/_/g, ' ')}: ${val}`)
        }
      })
  }
  return parts.join(' | ')
}

/** Plain-text rendering of the visible report set (used for Copy + Share). */
function buildReportText(reports: GeneratedReportRow[]): string {
  const header = 'Control Room — Shift & Performance Reports'
  const lines = reports.map((r) => {
    const name = resolveTemplateName(r.template)
    const creator = resolveCreatorName(r.creator)
    const summary = summarizeData(r.report_data)
    return [
      `• ${name}`,
      `  Date: ${r.report_date}  Shift: ${r.shift_type ?? '—'}`,
      `  Generated: ${new Date(r.generated_at).toLocaleString()}`,
      `  By: ${creator}`,
      summary ? `  Summary: ${summary}` : '',
      r.pdf_url ? `  Document: ${r.pdf_url}` : '  Document: Unavailable',
    ]
      .filter(Boolean)
      .join('\n')
  })
  return [
    header,
    `(${reports.length} report${reports.length === 1 ? '' : 's'})`,
    '',
    ...lines,
  ].join('\n')
}

/** CSV rendering of the visible report set (used for Export). */
function buildReportCsv(reports: GeneratedReportRow[]): string {
  const header = [
    'Report Name',
    'Report Date',
    'Shift Type',
    'Generated At',
    'Generated By',
    'Summary',
    'PDF URL',
  ]
  const escape = (val: string) => `"${val.replace(/"/g, '""')}"`
  const rows = reports.map((r) =>
    [
      resolveTemplateName(r.template),
      r.report_date,
      r.shift_type ?? '',
      new Date(r.generated_at).toLocaleString(),
      resolveCreatorName(r.creator),
      summarizeData(r.report_data),
      r.pdf_url ?? '',
    ]
      .map((c) => escape(String(c)))
      .join(',')
  )
  return [header.map(escape).join(','), ...rows].join('\n')
}

// AGENT-TRACE: clipboard write with execCommand fallback — jsdom / insecure
// contexts expose no navigator.clipboard, so we degrade gracefully.
async function copyTextToClipboard(text: string): Promise<boolean> {
  try {
    if (typeof navigator !== 'undefined' && navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(text)
      return true
    }
  } catch {
    // fall through to legacy path
  }
  try {
    if (typeof document !== 'undefined') {
      const ta = document.createElement('textarea')
      ta.value = text
      ta.style.position = 'fixed'
      ta.style.opacity = '0'
      document.body.appendChild(ta)
      ta.focus()
      ta.select()
      const ok = document.execCommand('copy')
      document.body.removeChild(ta)
      return ok
    }
  } catch {
    return false
  }
  return false
}

function triggerDownload(filename: string, content: string, mime: string) {
  if (typeof document === 'undefined' || typeof URL === 'undefined') return
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

type ActionState = 'idle' | 'busy' | 'done'

export function ReportActions({ reports }: ReportActionsProps) {
  const [copyState, setCopyState] = useState<ActionState>('idle')
  const [shareState, setShareState] = useState<ActionState>('idle')
  const [exportState, setExportState] = useState<ActionState>('idle')

  const isEmpty = reports.length === 0

  const handleCopy = useCallback(async () => {
    if (isEmpty) {
      toast.info('No reports to copy — adjust your filters.')
      return
    }
    setCopyState('busy')
    const ok = await copyTextToClipboard(buildReportText(reports))
    if (ok) {
      setCopyState('done')
      toast.success(
        `Copied ${reports.length} report${reports.length === 1 ? '' : 's'} to clipboard.`
      )
      setTimeout(() => setCopyState('idle'), 1500)
    } else {
      setCopyState('idle')
      toast.error('Unable to access clipboard in this browser.')
    }
  }, [isEmpty, reports])

  const handleShare = useCallback(async () => {
    if (isEmpty) {
      toast.info('No reports to share — adjust your filters.')
      return
    }
    setShareState('busy')
    const text = buildReportText(reports)
    const url = typeof window !== 'undefined' ? window.location.href : ''
    // AGENT-TRACE: prefer the native share sheet (mobile / PWA), else fall
    // back to copying a shareable block (link + summary) to the clipboard.
    try {
      if (typeof navigator !== 'undefined' && typeof navigator.share === 'function') {
        await navigator.share({ title: 'Control Room Reports', text, url })
        setShareState('idle')
        return
      }
    } catch {
      // user cancelled or share failed — fall back to clipboard below
    }
    const shared = await copyTextToClipboard(`${text}\n\n${url}`)
    setShareState('idle')
    if (shared) {
      toast.success('Shareable report link copied to clipboard.')
    } else {
      toast.error('Sharing is not supported in this browser.')
    }
  }, [isEmpty, reports])

  const handleExport = useCallback(() => {
    if (isEmpty) {
      toast.info('No reports to export — adjust your filters.')
      return
    }
    setExportState('busy')
    const stamp = new Date().toISOString().slice(0, 10)
    triggerDownload(
      `control-room-reports-${stamp}.csv`,
      buildReportCsv(reports),
      'text/csv;charset=utf-8'
    )
    setExportState('idle')
    toast.success(`Exported ${reports.length} report${reports.length === 1 ? '' : 's'} to CSV.`)
  }, [isEmpty, reports])

  const handlePrint = useCallback(() => {
    if (isEmpty) {
      toast.info('No reports to print — adjust your filters.')
      return
    }
    if (typeof window !== 'undefined') {
      window.print()
      toast.message('Opening print dialog for the current report view.')
    }
  }, [isEmpty])

  return (
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
      <p className="text-xs text-arch-text-muted">
        {isEmpty
          ? 'No reports match the current filters.'
          : `${reports.length} report${reports.length === 1 ? '' : 's'} selected by current filters.`}
      </p>
      <div className="flex flex-wrap items-center gap-2">
        <Button
          variant="secondary"
          size="sm"
          onClick={handleCopy}
          disabled={isEmpty}
          aria-label="Copy reports to clipboard"
        >
          {copyState === 'busy' ? (
            <Loader2 className="w-3.5 h-3.5 animate-spin" />
          ) : copyState === 'done' ? (
            <Check className="w-3.5 h-3.5" />
          ) : (
            <Copy className="w-3.5 h-3.5" />
          )}
          {copyState === 'done' ? 'Copied' : 'Copy to clipboard'}
        </Button>

        <Button
          variant="secondary"
          size="sm"
          onClick={handleShare}
          disabled={isEmpty}
          aria-label="Share reports"
        >
          {shareState === 'busy' ? (
            <Loader2 className="w-3.5 h-3.5 animate-spin" />
          ) : (
            <Share2 className="w-3.5 h-3.5" />
          )}
          Share
        </Button>

        <Button
          variant="primary"
          size="sm"
          onClick={handleExport}
          disabled={isEmpty}
          aria-label="Export reports to CSV"
        >
          {exportState === 'busy' ? (
            <Loader2 className="w-3.5 h-3.5 animate-spin" />
          ) : (
            <Download className="w-3.5 h-3.5" />
          )}
          Export
        </Button>

        <Button
          variant="ghost"
          size="sm"
          onClick={handlePrint}
          disabled={isEmpty}
          aria-label="Print reports"
        >
          <Printer className="w-3.5 h-3.5" />
          Print
        </Button>
      </div>
    </div>
  )
}
