/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type AuthAalLevel = 'aal1' | 'aal2' | 'aal3'

export type AuthCodeChallengeMethod = 'plain' | 's256'

export type AuthFactorStatus = 'unverified' | 'verified'

export type AuthFactorType = 'phone' | 'totp' | 'webauthn'

export type AuthOauthAuthorizationStatus = 'approved' | 'denied' | 'expired' | 'pending'

export type AuthOauthClientType = 'confidential' | 'public'

export type AuthOauthRegistrationType = 'dynamic' | 'manual'

export type AuthOauthResponseType = 'code'

export type AuthOneTimeTokenType =
  | 'confirmation_token'
  | 'email_change_token_current'
  | 'email_change_token_new'
  | 'phone_change_token'
  | 'reauthentication_token'
  | 'recovery_token'

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export type IncidentType = 'equipment-damage' | 'incident' | 'lost-time' | 'near-miss'

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>

export type Json = JsonValue

export type JsonArray = JsonValue[]

export type JsonObject = {
  [x: string]: JsonValue | undefined
}

export type JsonPrimitive = boolean | number | string | null

export type JsonValue = JsonArray | JsonObject | JsonPrimitive

export type MemoryType = 'episodic' | 'semantic'

export type Numeric = ColumnType<string, number | string, number | string>

export type ShiftStatusType = 'closed' | 'open'

export type ShiftType = 'day' | 'night'

export type StorageBuckettype = 'ANALYTICS' | 'STANDARD' | 'VECTOR'

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface _RealtimeExtensions {
  id: string
  inserted_at: Timestamp
  settings: Json | null
  tenant_external_id: string | null
  type: string | null
  updated_at: Timestamp
}

export interface _RealtimeFeatureFlags {
  enabled: Generated<boolean>
  id: string
  inserted_at: Timestamp
  name: string
  updated_at: Timestamp
}

export interface _RealtimeSchemaMigrations {
  inserted_at: Timestamp | null
  version: Int8
}

export interface _RealtimeTenants {
  broadcast_adapter: Generated<string | null>
  client_presence_window_ms: number | null
  external_id: string | null
  feature_flags: Generated<Json>
  id: string
  inserted_at: Timestamp
  jwt_jwks: Json | null
  jwt_secret: string | null
  max_bytes_per_second: Generated<number>
  max_channels_per_client: Generated<number>
  max_client_presence_events_per_window: number | null
  max_concurrent_users: Generated<number>
  max_events_per_second: Generated<number>
  max_joins_per_second: Generated<number>
  max_payload_size_in_kb: Generated<number | null>
  max_presence_events_per_second: Generated<number | null>
  migrations_ran: Generated<number | null>
  name: string | null
  notify_private_alpha: Generated<boolean | null>
  postgres_cdc_default: Generated<string | null>
  presence_enabled: Generated<boolean>
  private_only: Generated<boolean>
  suspend: Generated<boolean | null>
  updated_at: Timestamp
}

export interface AccessLogs {
  access_granted: Generated<boolean | null>
  access_type: string
  alcohol_tested: Generated<string>
  badge_id: string | null
  denial_reason: string | null
  department_id: string | null
  device_id: string | null
  direction: string
  gate_location: string
  id: Generated<string>
  operator: string | null
  scanned_at: Generated<Timestamp | null>
}

export interface AccessLogsArchive {
  access_granted: Generated<boolean | null>
  access_type: string
  alcohol_tested: Generated<string>
  archived_week_start: Generated<Timestamp>
  badge_id: string | null
  denial_reason: string | null
  department_id: string | null
  direction: string
  gate_location: string
  id: Generated<string>
  scanned_at: Generated<Timestamp | null>
}

export interface AdminAuditTrail {
  action: string
  created_at: Generated<Timestamp>
  department_id: string
  details: Json | null
  entity_id: string | null
  entity_type: string
  id: Generated<string>
  ip_address: string | null
  performed_by: string | null
}

export interface AiUsageLogs {
  completion_tokens: Generated<number>
  created_at: Generated<Timestamp>
  estimated_cost_usd: Generated<Numeric>
  id: Generated<string>
  metadata: Generated<Json>
  model: string
  prompt_tokens: Generated<number>
  provider: string
  session_id: string
  total_tokens: Generated<number>
  user_id: string | null
}

export interface AlarmEscalationPolicy {
  created_at: Generated<Timestamp>
  delay_seconds: Generated<number>
  department_id: string
  id: Generated<string>
  notification_channels: Generated<string[]>
  severity: string
  updated_at: Generated<Timestamp>
}

export interface AlarmEvents {
  acknowledged_at: Timestamp | null
  acknowledged_by: string | null
  created_at: Generated<Timestamp>
  department_id: string
  equipment_id: string
  id: Generated<string>
  message: string
  severity: string
  status: Generated<string>
  updated_at: Generated<Timestamp>
  value: Numeric | null
}

export interface AuditActivityLogs {
  created_at: Generated<Timestamp | null>
  id: Generated<string>
  new_data: Json | null
  old_data: Json | null
  operation: string
  performed_by: Generated<string | null>
  record_id: string | null
  table_name: string
}

export interface AuditLogs {
  /**
   * DML operation: insert, update, delete
   */
  action: string
  created_at: Generated<Timestamp>
  department_id: string | null
  id: Generated<string>
  /**
   * Client IP address at time of change
   */
  ip_address: string | null
  /**
   * Row state after the change (null for deletes)
   */
  new_data: Json | null
  /**
   * Row state before the change (null for inserts)
   */
  old_data: Json | null
  performed_by: string | null
  record_id: string | null
  table_name: string
  /**
   * Client user agent string
   */
  user_agent: string | null
}

export interface AuthAuditLogEntries {
  created_at: Timestamp | null
  id: string
  instance_id: string | null
  ip_address: Generated<string>
  payload: Json | null
}

export interface AuthCustomOauthProviders {
  acceptable_client_ids: Generated<string[]>
  attribute_mapping: Generated<Json>
  authorization_params: Generated<Json>
  authorization_url: string | null
  cached_discovery: Json | null
  client_id: string
  client_secret: string
  created_at: Generated<Timestamp>
  discovery_cached_at: Timestamp | null
  discovery_url: string | null
  email_optional: Generated<boolean>
  enabled: Generated<boolean>
  id: Generated<string>
  identifier: string
  issuer: string | null
  jwks_uri: string | null
  name: string
  pkce_enabled: Generated<boolean>
  provider_type: string
  scopes: Generated<string[]>
  skip_nonce_check: Generated<boolean>
  token_url: string | null
  updated_at: Generated<Timestamp>
  userinfo_url: string | null
}

export interface AuthFlowState {
  auth_code: string | null
  auth_code_issued_at: Timestamp | null
  authentication_method: string
  code_challenge: string | null
  code_challenge_method: AuthCodeChallengeMethod | null
  created_at: Timestamp | null
  email_optional: Generated<boolean>
  id: string
  invite_token: string | null
  linking_target_id: string | null
  oauth_client_state_id: string | null
  provider_access_token: string | null
  provider_refresh_token: string | null
  provider_type: string
  referrer: string | null
  updated_at: Timestamp | null
  user_id: string | null
}

export interface AuthIdentities {
  created_at: Timestamp | null
  /**
   * Auth: Email is a generated column that references the optional email property in the identity_data
   */
  email: Generated<string | null>
  id: Generated<string>
  identity_data: Json
  last_sign_in_at: Timestamp | null
  provider: string
  provider_id: string
  updated_at: Timestamp | null
  user_id: string
}

export interface AuthInstances {
  created_at: Timestamp | null
  id: string
  raw_base_config: string | null
  updated_at: Timestamp | null
  uuid: string | null
}

export interface AuthMfaAmrClaims {
  authentication_method: string
  created_at: Timestamp
  id: string
  session_id: string
  updated_at: Timestamp
}

export interface AuthMfaChallenges {
  created_at: Timestamp
  factor_id: string
  id: string
  ip_address: string
  otp_code: string | null
  verified_at: Timestamp | null
  web_authn_session_data: Json | null
}

export interface AuthMfaFactors {
  created_at: Timestamp
  factor_type: AuthFactorType
  friendly_name: string | null
  id: string
  last_challenged_at: Timestamp | null
  /**
   * Stores the latest WebAuthn challenge data including attestation/assertion for customer verification
   */
  last_webauthn_challenge_data: Json | null
  phone: string | null
  secret: string | null
  status: AuthFactorStatus
  updated_at: Timestamp
  user_id: string
  web_authn_aaguid: string | null
  web_authn_credential: Json | null
}

export interface AuthOauthAuthorizations {
  approved_at: Timestamp | null
  authorization_code: string | null
  authorization_id: string
  client_id: string
  code_challenge: string | null
  code_challenge_method: AuthCodeChallengeMethod | null
  created_at: Generated<Timestamp>
  expires_at: Generated<Timestamp>
  id: string
  nonce: string | null
  redirect_uri: string
  resource: string | null
  response_type: Generated<AuthOauthResponseType>
  scope: string
  state: string | null
  status: Generated<AuthOauthAuthorizationStatus>
  user_id: string | null
}

export interface AuthOauthClients {
  client_name: string | null
  client_secret_hash: string | null
  client_type: Generated<AuthOauthClientType>
  client_uri: string | null
  created_at: Generated<Timestamp>
  deleted_at: Timestamp | null
  grant_types: string
  id: string
  logo_uri: string | null
  redirect_uris: string
  registration_type: AuthOauthRegistrationType
  token_endpoint_auth_method: string
  updated_at: Generated<Timestamp>
}

export interface AuthOauthClientStates {
  code_verifier: string | null
  created_at: Timestamp
  id: string
  provider_type: string
}

export interface AuthOauthConsents {
  client_id: string
  granted_at: Generated<Timestamp>
  id: string
  revoked_at: Timestamp | null
  scopes: string
  user_id: string
}

export interface AuthOneTimeTokens {
  created_at: Generated<Timestamp>
  id: string
  relates_to: string
  token_hash: string
  token_type: AuthOneTimeTokenType
  updated_at: Generated<Timestamp>
  user_id: string
}

export interface AuthRefreshTokens {
  created_at: Timestamp | null
  id: Generated<Int8>
  instance_id: string | null
  parent: string | null
  revoked: boolean | null
  session_id: string | null
  token: string | null
  updated_at: Timestamp | null
  user_id: string | null
}

export interface AuthSamlProviders {
  attribute_mapping: Json | null
  created_at: Timestamp | null
  entity_id: string
  id: string
  metadata_url: string | null
  metadata_xml: string
  name_id_format: string | null
  sso_provider_id: string
  updated_at: Timestamp | null
}

export interface AuthSamlRelayStates {
  created_at: Timestamp | null
  flow_state_id: string | null
  for_email: string | null
  id: string
  redirect_to: string | null
  request_id: string
  sso_provider_id: string
  updated_at: Timestamp | null
}

export interface AuthSchemaMigrations {
  version: string
}

export interface AuthSessions {
  aal: AuthAalLevel | null
  created_at: Timestamp | null
  factor_id: string | null
  id: string
  ip: string | null
  /**
   * Auth: Not after is a nullable column that contains a timestamp after which the session should be regarded as expired.
   */
  not_after: Timestamp | null
  oauth_client_id: string | null
  /**
   * Holds the ID (counter) of the last issued refresh token.
   */
  refresh_token_counter: Int8 | null
  /**
   * Holds a HMAC-SHA256 key used to sign refresh tokens for this session.
   */
  refresh_token_hmac_key: string | null
  refreshed_at: Timestamp | null
  scopes: string | null
  tag: string | null
  updated_at: Timestamp | null
  user_agent: string | null
  user_id: string
}

export interface AuthSsoDomains {
  created_at: Timestamp | null
  domain: string
  id: string
  sso_provider_id: string
  updated_at: Timestamp | null
}

export interface AuthSsoProviders {
  created_at: Timestamp | null
  disabled: boolean | null
  id: string
  /**
   * Auth: Uniquely identifies a SSO provider according to a user-chosen resource ID (case insensitive), useful in infrastructure as code.
   */
  resource_id: string | null
  updated_at: Timestamp | null
}

export interface AuthUsers {
  aud: string | null
  banned_until: Timestamp | null
  confirmation_sent_at: Timestamp | null
  confirmation_token: string | null
  confirmed_at: Generated<Timestamp | null>
  created_at: Timestamp | null
  deleted_at: Timestamp | null
  email: string | null
  email_change: string | null
  email_change_confirm_status: Generated<number | null>
  email_change_sent_at: Timestamp | null
  email_change_token_current: Generated<string | null>
  email_change_token_new: string | null
  email_confirmed_at: Timestamp | null
  encrypted_password: string | null
  id: string
  instance_id: string | null
  invited_at: Timestamp | null
  is_anonymous: Generated<boolean>
  /**
   * Auth: Set this column to true when the account comes from SSO. These accounts can have duplicate emails.
   */
  is_sso_user: Generated<boolean>
  is_super_admin: boolean | null
  last_sign_in_at: Timestamp | null
  phone: Generated<string | null>
  phone_change: Generated<string | null>
  phone_change_sent_at: Timestamp | null
  phone_change_token: Generated<string | null>
  phone_confirmed_at: Timestamp | null
  raw_app_meta_data: Json | null
  raw_user_meta_data: Json | null
  reauthentication_sent_at: Timestamp | null
  reauthentication_token: Generated<string | null>
  recovery_sent_at: Timestamp | null
  recovery_token: string | null
  role: string | null
  updated_at: Timestamp | null
}

export interface AuthWebauthnChallenges {
  challenge_type: string
  created_at: Generated<Timestamp>
  expires_at: Timestamp
  id: Generated<string>
  session_data: Json
  user_id: string | null
}

export interface AuthWebauthnCredentials {
  aaguid: string | null
  attestation_type: Generated<string>
  backed_up: Generated<boolean>
  backup_eligible: Generated<boolean>
  created_at: Generated<Timestamp>
  credential_id: Buffer
  friendly_name: Generated<string>
  id: Generated<string>
  last_used_at: Timestamp | null
  public_key: Buffer
  sign_count: Generated<Int8>
  transports: Generated<Json>
  updated_at: Generated<Timestamp>
  user_id: string
}

export interface Badges {
  /**
   * Denormalized department for fast dashboard queries. Derived from personnel or visitor host.
   */
  department_id: string | null
  entity_type: string
  /**
   * Links badge to equipment asset
   */
  equipment_id: string | null
  expires_at: Timestamp | null
  /**
   * Links badge to fleet vehicle when entity_type = vehicle
   */
  fleet_id: string | null
  id: Generated<string>
  is_active: Generated<boolean | null>
  issued_at: Generated<Timestamp | null>
  personnel_id: string | null
  qr_code: string
  revoked_at: Timestamp | null
  visitor_id: string | null
}

export interface BlastDesigns {
  actual_holes: number | null
  actual_tonnes: Numeric | null
  blast_date: Timestamp | null
  blast_name: string
  block_id: string | null
  created_at: Generated<Timestamp>
  department_id: string
  designed_by: string | null
  designed_holes: Generated<number>
  designed_tonnes: Numeric | null
  explosive_type: string | null
  id: Generated<string>
  notes: string | null
  pattern_id: string | null
  status: Generated<string>
  total_explosive_kg: Numeric | null
  updated_at: Generated<Timestamp>
}

export interface Breakdowns {
  completed_by: string | null
  created_at: Generated<Timestamp>
  created_by: string | null
  /**
   * Date equipment was brought in for repair
   */
  date_in: Timestamp
  /**
   * Date equipment returned to service
   */
  date_out: Timestamp | null
  /**
   * Soft delete timestamp
   */
  deleted_at: Timestamp | null
  department_id: string
  /**
   * Automatically calculated duration between book-in and book-out
   */
  duration_hours: Generated<Numeric | null>
  /**
   * Equipment fleet identifier
   */
  fleet_id: string
  id: Generated<string>
  idempotency_key: Generated<string | null>
  last_synced_at: Generated<Timestamp | null>
  machine_name: string | null
  machine_type: string
  /**
   * Flag for incomplete book-in paperwork
   */
  missing_book_in: Generated<boolean>
  reason: string
  repair_notes: string | null
  status: Generated<string>
  sync_status: Generated<string | null>
  time_in: Generated<string | null>
  time_out: string | null
  updated_at: Generated<Timestamp>
}

export interface CardPrintHistory {
  badge_id: string | null
  card_type: string
  department_id: string
  employee_name: string
  id: Generated<string>
  notes: string | null
  print_status: Generated<string>
  printed_at: Generated<Timestamp>
  printed_by: string | null
  printer_name: string | null
  qr_code: string | null
}

export interface Certifications {
  certification: string
  created_at: Generated<Timestamp>
  department_id: string
  employee_id: string | null
  employee_name: string
  expiry_date: Timestamp
  id: Generated<string>
  issue_date: Timestamp
  issued_by: string | null
  notes: string | null
  role: string | null
  updated_at: Generated<Timestamp>
}

export interface CronJob {
  active: Generated<boolean>
  command: string
  database: Generated<string>
  jobid: Generated<Int8>
  jobname: string | null
  nodename: Generated<string>
  nodeport: Generated<number>
  schedule: string
  username: Generated<string>
}

export interface CronJobRunDetails {
  command: string | null
  database: string | null
  end_time: Timestamp | null
  job_pid: number | null
  jobid: Int8 | null
  return_message: string | null
  runid: Generated<Int8>
  start_time: Timestamp | null
  status: string | null
  username: string | null
}

export interface DailyLogs {
  created_at: Generated<Timestamp>
  created_by: string | null
  department_id: string
  id: Generated<string>
  idempotency_key: Generated<string | null>
  last_synced_at: Generated<Timestamp | null>
  log_date: Timestamp
  notes: string | null
  shift: string
  sync_status: Generated<string | null>
  updated_at: Timestamp | null
  updated_by: string | null
}

export interface DailyLogsLegacy {
  created_at: Generated<Timestamp>
  created_by: string | null
  department_id: string
  id: Generated<string>
  idempotency_key: Generated<string | null>
  last_synced_at: Generated<Timestamp | null>
  /**
   * Date of the shift
   */
  log_date: Timestamp
  /**
   * General shift notes
   */
  notes: string | null
  /**
   * Enum: day, night
   */
  shift: Generated<ShiftType>
  sync_status: Generated<string | null>
  updated_at: Timestamp | null
  updated_by: string | null
}

export interface DelayCategories {
  color: Generated<string>
  deleted_at: Timestamp | null
  icon: string | null
  id: Generated<string>
  name: string
  /**
   * Display ordering in dropdowns
   */
  sort_order: Generated<number>
  updated_at: Timestamp | null
}

export interface Departments {
  /**
   * Theme color key (blue, emerald, blue, etc.)
   */
  color: string
  created_at: Generated<Timestamp>
  /**
   * Soft delete timestamp
   */
  deleted_at: Timestamp | null
  description: string | null
  /**
   * Human-readable department name
   */
  display_name: string
  /**
   * Lucide icon identifier
   */
  icon: string
  id: Generated<string>
  /**
   * URL-safe unique slug for routing
   */
  name: string
  /**
   * AI assistant personality/mission statement (SOUL.md) for department-specific agent behavior
   */
  personality: string | null
  updated_at: Timestamp | null
}

export interface Documents {
  content: Generated<Json>
  created_at: Generated<Timestamp>
  created_by: string | null
  deleted_at: Timestamp | null
  department_id: string
  file_name: string | null
  file_path: string | null
  file_size: Int8 | null
  id: Generated<string>
  mime_type: string | null
  title: Generated<string>
  updated_at: Generated<Timestamp>
}

export interface DocumentVersions {
  content: Generated<Json>
  created_at: Generated<Timestamp>
  created_by: string | null
  document_id: string
  id: Generated<string>
  summary: string | null
  title: string
  version_number: number
}

export interface DozerRolls {
  area_covered_sqm: Numeric | null
  /**
   * Number of blade passes
   */
  blade_passes: Generated<number>
  created_at: Generated<Timestamp>
  department_id: string
  hours_operated: Numeric | null
  id: Generated<string>
  machine_id: string
  material_moved_tonnes: Numeric | null
  notes: string | null
  operator_id: string | null
  /**
   * Number of push operations
   */
  push_count: Generated<number>
  roll_date: Timestamp
  shift_type: string
  updated_at: Generated<Timestamp>
}

export interface DozerRollsArchive {
  area_covered_sqm: Numeric | null
  /**
   * Number of blade passes
   */
  blade_passes: Generated<number>
  created_at: Generated<Timestamp>
  department_id: string
  hours_operated: Numeric | null
  id: Generated<string>
  machine_id: string
  material_moved_tonnes: Numeric | null
  notes: string | null
  operator_id: string | null
  /**
   * Number of push operations
   */
  push_count: Generated<number>
  roll_date: Timestamp
  shift_type: string
  updated_at: Generated<Timestamp>
}

export interface DrillOperations {
  block_drilled: string | null
  close_hours: Numeric | null
  /**
   * Free-text notes for the shift.
   */
  comments: string | null
  created_at: Generated<Timestamp>
  created_by: string | null
  delay_blasting: Generated<Numeric | null>
  delay_elec_breakdown: Generated<Numeric | null>
  delay_get: Generated<Numeric | null>
  delay_lunch_breaks: Generated<Numeric | null>
  delay_maintenance: Generated<Numeric | null>
  delay_mech_breakdown: Generated<Numeric | null>
  delay_natural: Generated<Numeric | null>
  delay_no_operator: Generated<Numeric | null>
  delay_non_prod_other: Generated<Numeric | null>
  delay_safety_talks: Generated<Numeric | null>
  delay_tramming: Generated<Numeric | null>
  department_id: string
  /**
   * Engineering / maintenance delays, in minutes.
   */
  engineering_delays_minutes: Generated<Numeric | null>
  /**
   * External (not attributable to machine/operator) delays, in minutes.
   */
  external_delays_minutes: Generated<Numeric | null>
  holes: Generated<number | null>
  id: Generated<string>
  machine_id: string
  meters_drilled: Generated<Numeric | null>
  notes: string | null
  open_hours: Numeric | null
  operation_date: Generated<Timestamp>
  operator_id: string | null
  operator_name: string | null
  /**
   * Production-attributable delays, in minutes.
   */
  production_delays_minutes: Generated<Numeric | null>
  shift_id: string | null
  shift_type: string | null
  /**
   * Free-text site label (e.g. N2-B4, Pit C West).
   */
  site: string | null
  /**
   * Standard non-productive delay (lunch, safety talks). Defaults to 2 hours, editable.
   */
  standard_delays_hours: Generated<Numeric | null>
  status: Generated<string | null>
  total_hours: Generated<Numeric | null>
  updated_at: Generated<Timestamp>
  updated_by: string | null
}

export interface DrillOperationsArchive {
  block_drilled: string | null
  close_hours: Numeric | null
  created_at: Generated<Timestamp>
  created_by: string | null
  delay_blasting: Generated<Numeric | null>
  delay_elec_breakdown: Generated<Numeric | null>
  delay_get: Generated<Numeric | null>
  delay_lunch_breaks: Generated<Numeric | null>
  delay_maintenance: Generated<Numeric | null>
  delay_mech_breakdown: Generated<Numeric | null>
  delay_natural: Generated<Numeric | null>
  delay_no_operator: Generated<Numeric | null>
  delay_non_prod_other: Generated<Numeric | null>
  delay_safety_talks: Generated<Numeric | null>
  delay_tramming: Generated<Numeric | null>
  department_id: string
  holes: Generated<number | null>
  id: Generated<string>
  machine_id: string
  meters_drilled: Generated<Numeric | null>
  notes: string | null
  open_hours: Numeric | null
  operation_date: Generated<Timestamp>
  operator_id: string | null
  operator_name: string | null
  shift_id: string | null
  shift_type: string | null
  status: Generated<string | null>
  total_hours: Generated<Numeric | null>
  updated_at: Generated<Timestamp>
  updated_by: string | null
}

export interface DrillPatterns {
  approved_by: string | null
  block_id: string | null
  burden_m: Generated<Numeric>
  created_at: Generated<Timestamp>
  department_id: string
  designed_by: string | null
  hole_depth_m: Generated<Numeric>
  hole_diameter_mm: Generated<Numeric>
  id: Generated<string>
  notes: string | null
  pattern_name: string
  pattern_type: string
  powder_factor: Numeric | null
  spacing_m: Generated<Numeric>
  status: Generated<string>
  stemming_m: Generated<Numeric>
  sub_drill_m: Generated<Numeric>
  total_holes: Generated<number>
  updated_at: Generated<Timestamp>
}

export interface EmbeddingCache {
  created_at: Generated<Timestamp>
  embedding: string
  text_hash: string
  user_id: string
}

export interface Employees {
  /**
   * Additional departments this user can access
   */
  accessible_departments: Generated<string[] | null>
  /**
   * FK to auth.users (Supabase Auth)
   */
  auth_id: string
  created_at: Generated<Timestamp>
  /**
   * Soft delete timestamp
   */
  deleted_at: Timestamp | null
  /**
   * Primary department assignment
   */
  department_id: string | null
  employee_code: string | null
  full_name: string
  id: Generated<string>
  pin_hash: string | null
  /**
   * Enum: admin, supervisor, operator, maintenance, viewer, trainer, relief
   */
  role: Generated<string>
  updated_at: Timestamp | null
}

export interface EngineeringNotes {
  action_taken: string
  created_at: Generated<Timestamp>
  created_by: string | null
  department_id: string
  description: string
  id: Generated<string>
  /**
   * Category of engineering issue
   */
  issue_type: string
  machine_id: string | null
  note_date: Timestamp
  requires_follow_up: Generated<boolean>
  resolved_at: Timestamp | null
  /**
   * Impact level: low, medium, high, critical
   */
  severity: string
  shift_type: string
  /**
   * Resolution workflow status
   */
  status: Generated<string>
  updated_at: Generated<Timestamp>
}

export interface EngineeringNotesArchive {
  action_taken: string
  created_at: Generated<Timestamp>
  created_by: string | null
  department_id: string
  description: string
  id: Generated<string>
  /**
   * Category of engineering issue
   */
  issue_type: string
  machine_id: string | null
  note_date: Timestamp
  requires_follow_up: Generated<boolean>
  resolved_at: Timestamp | null
  /**
   * Impact level: low, medium, high, critical
   */
  severity: string
  shift_type: string
  /**
   * Resolution workflow status
   */
  status: Generated<string>
  updated_at: Generated<Timestamp>
}

export interface EnvironmentalIncidents {
  closed_at: Timestamp | null
  corrective_action: string | null
  created_at: Generated<Timestamp>
  department_id: string
  description: string
  id: Generated<string>
  incident_date: Timestamp
  incident_type: string
  location: string | null
  regulatory_notified: Generated<boolean>
  reported_by: string | null
  root_cause: string | null
  severity: Generated<string>
  status: Generated<string>
  updated_at: Generated<Timestamp>
}

export interface EnvironmentalReadings {
  created_at: Generated<Timestamp>
  department_id: string
  id: Generated<string>
  location: string | null
  notes: string | null
  reading_date: Timestamp
  reading_type: string
  recorded_by: string | null
  status: Generated<string>
  unit: Generated<string>
  updated_at: Generated<Timestamp>
  value: Generated<Numeric>
}

export interface Equipment {
  assigned_to: string | null
  calibration_expiry: Timestamp | null
  created_at: Generated<Timestamp | null>
  department_id: string | null
  equip_code: string
  equipment_type: string
  id: Generated<string>
  manufacturer: string | null
  model: string | null
  serial_number: string | null
  status: Generated<string>
  updated_at: Generated<Timestamp | null>
}

export interface ExcavatorActivity {
  activity_date: Timestamp
  /**
   * Average loader cycle time in seconds
   */
  avg_cycle_time_seconds: number | null
  block_mined_id: string | null
  created_at: Generated<Timestamp>
  department_id: string
  estimated_tonnes: Numeric | null
  id: Generated<string>
  loads: Generated<number>
  machine_id: string
  /**
   * Type of material being excavated
   */
  material_type: string | null
  notes: string | null
  operator_id: string | null
  passes: Generated<number>
  shift_type: string
  site_id: string | null
  updated_at: Generated<Timestamp>
}

export interface ExcavatorActivityArchive {
  activity_date: Timestamp
  /**
   * Average loader cycle time in seconds
   */
  avg_cycle_time_seconds: number | null
  block_mined_id: string | null
  created_at: Generated<Timestamp>
  department_id: string
  estimated_tonnes: Numeric | null
  id: Generated<string>
  loads: Generated<number>
  machine_id: string
  /**
   * Type of material being excavated
   */
  material_type: string | null
  notes: string | null
  operator_id: string | null
  passes: Generated<number>
  shift_type: string
  site_id: string | null
  updated_at: Generated<Timestamp>
}

export interface ExcavatorDumperAssignments {
  created_at: Generated<Timestamp>
  dumper_machine_id: string
  excavator_activity_id: string
  id: Generated<string>
  material_type: Generated<string>
  notes: string | null
  session_index: Generated<number>
  /**
   * Total bank cubic metres moved
   */
  total_bcm: Numeric | null
  total_loads: Generated<number>
  updated_at: Generated<Timestamp>
}

export interface ExcavatorDumperAssignmentsArchive {
  created_at: Generated<Timestamp>
  dumper_machine_id: string
  excavator_activity_id: string
  id: Generated<string>
  material_type: Generated<string>
  notes: string | null
  /**
   * Total bank cubic metres moved
   */
  total_bcm: Numeric | null
  total_loads: Generated<number>
  updated_at: Generated<Timestamp>
}

export interface ExtensionsPgStatStatements {
  calls: Int8 | null
  dbid: number | null
  jit_deform_count: Int8 | null
  jit_deform_time: number | null
  jit_emission_count: Int8 | null
  jit_emission_time: number | null
  jit_functions: Int8 | null
  jit_generation_time: number | null
  jit_inlining_count: Int8 | null
  jit_inlining_time: number | null
  jit_optimization_count: Int8 | null
  jit_optimization_time: number | null
  local_blk_read_time: number | null
  local_blk_write_time: number | null
  local_blks_dirtied: Int8 | null
  local_blks_hit: Int8 | null
  local_blks_read: Int8 | null
  local_blks_written: Int8 | null
  max_exec_time: number | null
  max_plan_time: number | null
  mean_exec_time: number | null
  mean_plan_time: number | null
  min_exec_time: number | null
  min_plan_time: number | null
  minmax_stats_since: Timestamp | null
  plans: Int8 | null
  query: string | null
  queryid: Int8 | null
  rows: Int8 | null
  shared_blk_read_time: number | null
  shared_blk_write_time: number | null
  shared_blks_dirtied: Int8 | null
  shared_blks_hit: Int8 | null
  shared_blks_read: Int8 | null
  shared_blks_written: Int8 | null
  stats_since: Timestamp | null
  stddev_exec_time: number | null
  stddev_plan_time: number | null
  temp_blk_read_time: number | null
  temp_blk_write_time: number | null
  temp_blks_read: Int8 | null
  temp_blks_written: Int8 | null
  toplevel: boolean | null
  total_exec_time: number | null
  total_plan_time: number | null
  userid: number | null
  wal_bytes: Numeric | null
  wal_fpi: Int8 | null
  wal_records: Int8 | null
}

export interface ExtensionsPgStatStatementsInfo {
  dealloc: Int8 | null
  stats_reset: Timestamp | null
}

export interface Fleet {
  created_at: Generated<Timestamp | null>
  department_id: string | null
  fleet_code: string
  id: Generated<string>
  last_service_date: Timestamp | null
  make: string | null
  model: string | null
  next_service_date: Timestamp | null
  registration_number: string | null
  status: Generated<string>
  updated_at: Generated<Timestamp | null>
  vehicle_type: string
  year: number | null
}

export interface FleetMaintenanceSchedule {
  actual_cost: Numeric | null
  actual_hours: Numeric | null
  assigned_to: string | null
  completed_date: Timestamp | null
  cost_estimate: Numeric | null
  created_at: Generated<Timestamp>
  department_id: string
  description: string
  estimated_hours: Numeric | null
  fleet_id: string | null
  id: Generated<string>
  notes: string | null
  parts_used: string[] | null
  scheduled_date: Timestamp
  service_type: string
  status: Generated<string>
  updated_at: Generated<Timestamp>
}

export interface FuelLogs {
  created_at: Generated<Timestamp>
  created_by: string | null
  daily_log_id: string
  department_id: string
  /**
   * Volume in litres with 2 decimal precision
   */
  diesel_litres: Generated<Numeric>
  id: Generated<string>
  log_date: Timestamp
  machine_id: string
  updated_at: Timestamp | null
  updated_by: string | null
}

export interface GeneratedReports {
  department_id: string
  generated_at: Generated<Timestamp>
  generated_by: string
  id: Generated<string>
  /**
   * URL to generated PDF (if exported)
   */
  pdf_url: string | null
  /**
   * JSON payload of report content
   */
  report_data: Json
  report_date: Timestamp
  shift_type: string | null
  template_id: string | null
  updated_at: Timestamp | null
}

export interface GradeControlSamples {
  ash_pct: Numeric | null
  block_id: string | null
  calorific_value: Numeric | null
  created_at: Generated<Timestamp>
  department_id: string
  id: Generated<string>
  lab_ref: string | null
  location: string | null
  moisture_pct: Numeric | null
  sample_date: Timestamp
  sample_type: string
  sample_weight_kg: Numeric | null
  sampled_by: string | null
  seam: string | null
  status: Generated<string>
  sulphur_pct: Numeric | null
  updated_at: Generated<Timestamp>
  volatile_matter_pct: Numeric | null
}

export interface HourlyLoads {
  created_at: Generated<Timestamp>
  created_by: string | null
  department_id: string
  hour_01: Generated<number>
  hour_02: Generated<number>
  hour_03: Generated<number>
  hour_04: Generated<number>
  hour_05: Generated<number>
  hour_06: Generated<number>
  hour_07: Generated<number>
  hour_08: Generated<number>
  hour_09: Generated<number>
  hour_10: Generated<number>
  hour_11: Generated<number>
  hour_12: Generated<number>
  id: Generated<string>
  load_date: Timestamp
  machine_id: string
  /**
   * Type of material: Waste or Coal
   */
  material_type: Generated<string>
  session_index: Generated<number>
  shift_type: string
  total_loads: Generated<number | null>
  updated_at: Generated<Timestamp>
  updated_by: string | null
}

export interface HourlyLoadsLegacy {
  created_at: Generated<Timestamp>
  created_by: string | null
  department_id: string
  hour_01: Generated<number>
  hour_02: Generated<number>
  hour_03: Generated<number>
  hour_04: Generated<number>
  hour_05: Generated<number>
  hour_06: Generated<number>
  hour_07: Generated<number>
  hour_08: Generated<number>
  hour_09: Generated<number>
  hour_10: Generated<number>
  hour_11: Generated<number>
  hour_12: Generated<number>
  id: Generated<string>
  load_date: Timestamp
  machine_id: string
  /**
   * Shift identifier (day 06-18 or night 18-06)
   */
  shift_type: string
  /**
   * Generated: sum of hour_01 through hour_12
   */
  total_loads: Generated<number | null>
  updated_at: Generated<Timestamp>
  updated_by: string | null
}

export interface JobSafetyAnalyses {
  approved_by: string | null
  created_at: Generated<Timestamp>
  department_id: string
  hazards_identified: Generated<number>
  id: Generated<string>
  job_description: string
  jsa_number: string
  location: string | null
  prepared_by: string | null
  reviewed_by: string | null
  risk_level: Generated<string>
  status: Generated<string>
  updated_at: Generated<Timestamp>
  valid_from: Timestamp
  valid_to: Timestamp | null
}

export interface MachineConfigurations {
  created_at: Generated<Timestamp>
  created_by: string | null
  department_id: string
  hydraulic_pressure: number
  id: Generated<string>
  power_allocation: number
  target_rpm: number
  updated_at: Generated<Timestamp>
  updated_by: string | null
}

export interface MachineHours {
  created_at: Generated<Timestamp>
  created_by: string | null
  daily_log_id: string
  department_id: string
  /**
   * Decimal hours with 2 decimal precision
   */
  hours_worked: Generated<Numeric>
  id: Generated<string>
  log_date: Timestamp
  machine_id: string
  updated_at: Timestamp | null
  updated_by: string | null
}

export interface MachineOperations {
  /**
   * Service meter reading at shift close (entered by operator/supervisor)
   */
  close_smr: Numeric | null
  created_at: Generated<Timestamp>
  created_by: string | null
  department_id: string
  /**
   * Operation end time (null if ongoing)
   */
  end_time: string | null
  /**
   * Engineering/breakdown delays
   */
  engineering_delay_minutes: Generated<number>
  /**
   * Standard 1h GET / diesel-refill downtime, applied to every machine until changed.
   */
  get_diesel_delay_minutes: Generated<number>
  /**
   * Generated: computed from end_time - start_time
   */
  hours_worked: Generated<Numeric | null>
  id: Generated<string>
  /**
   * Standard 1h lunch downtime, applied to every machine until changed.
   */
  lunch_delay_minutes: Generated<number>
  machine_id: string
  /**
   * Natural/weather delays
   */
  natural_delay_minutes: Generated<number>
  /**
   * Non-production delays (e.g. shift change, meetings)
   */
  non_production_delay_minutes: Generated<number>
  operator_id: string | null
  /**
   * Production-related delays (e.g. material shortage)
   */
  production_delay_minutes: Generated<number>
  /**
   * Standard 1h safety-talk downtime, applied to every machine until changed.
   */
  safety_talk_delay_minutes: Generated<number>
  shift_date: Timestamp
  shift_type: string
  site_id: string | null
  /**
   * Auto-calculated close_smr - start_smr
   */
  smr_total: Generated<Numeric | null>
  /**
   * Service meter reading at shift start (pulled from previous close)
   */
  start_smr: Numeric | null
  /**
   * Operation start time
   */
  start_time: string
  updated_at: Generated<Timestamp>
}

export interface MachineOperationsArchive {
  close_smr: Numeric | null
  created_at: Generated<Timestamp>
  created_by: string | null
  department_id: string
  /**
   * Operation end time (null if ongoing)
   */
  end_time: string | null
  engineering_delay_minutes: Generated<number>
  get_diesel_delay_minutes: number | null
  /**
   * Generated: computed from end_time - start_time
   */
  hours_worked: Generated<Numeric | null>
  id: Generated<string>
  lunch_delay_minutes: number | null
  machine_id: string
  natural_delay_minutes: Generated<number>
  non_production_delay_minutes: Generated<number>
  operator_id: string | null
  production_delay_minutes: Generated<number>
  safety_talk_delay_minutes: number | null
  shift_date: Timestamp
  shift_type: string
  site_id: string | null
  smr_total: Numeric | null
  start_smr: Numeric | null
  /**
   * Operation start time
   */
  start_time: string
  updated_at: Generated<Timestamp>
}

export interface Machines {
  active: Generated<boolean>
  /**
   * Payload factor for dump trucks (tonnes per load)
   */
  bin_factor: Numeric | null
  created_at: Generated<Timestamp>
  /**
   * Latest known close_smr; updated by control-room shift close
   */
  current_smr: Numeric | null
  /**
   * Soft delete timestamp
   */
  deleted_at: Timestamp | null
  department_id: string
  id: Generated<string>
  /**
   * Equipment class. Dumpers (articulated/rigid) require a bin_factor for tonnage math.
   */
  machine_category: string | null
  /**
   * Category of equipment (Drill Rig, Dump Truck, Excavator, etc.)
   */
  machine_type: string
  name: string
  /**
   * Admin-only: when true this machine is excluded from shift-completeness enforcement
   */
  report_exempt: Generated<boolean>
  serial_number: string | null
  /**
   * Current operational site assignment
   */
  site_id: string | null
  updated_at: Timestamp | null
}

export interface MachineTelemetry {
  alert_codes: string[] | null
  alert_count: Generated<number | null>
  ambient_temp: Numeric | null
  bit_depth: Numeric | null
  created_at: Generated<Timestamp>
  department_id: string
  engine_rpm: Numeric | null
  engine_temp: Numeric | null
  fuel_level: Numeric | null
  hole_depth: Numeric | null
  hydraulic_pressure: Numeric | null
  hydraulic_temp: Numeric | null
  id: Generated<string>
  machine_id: string
  mud_flow_rate: Numeric | null
  operating_hours: Numeric | null
  penetration_rate: Numeric | null
  recorded_at: Generated<Timestamp>
  rotation_torque: Numeric | null
  standpipe_pressure: Numeric | null
  vibration_level: Numeric | null
  weight_on_bit: Numeric | null
  year_month: Generated<string>
}

export interface MachineTelemetryArchive {
  alert_codes: string[] | null
  alert_count: Generated<number | null>
  ambient_temp: Numeric | null
  archived_at: Generated<Timestamp>
  bit_depth: Numeric | null
  created_at: Timestamp
  department_id: string
  engine_rpm: Numeric | null
  engine_temp: Numeric | null
  fuel_level: Numeric | null
  hole_depth: Numeric | null
  hydraulic_pressure: Numeric | null
  hydraulic_temp: Numeric | null
  id: string
  machine_id: string
  mud_flow_rate: Numeric | null
  operating_hours: Numeric | null
  penetration_rate: Numeric | null
  record_count: number
  recorded_at: Timestamp
  rotation_torque: Numeric | null
  standpipe_pressure: Numeric | null
  vibration_level: Numeric | null
  weight_on_bit: Numeric | null
  year_month: string
}

export interface MaterializedViewRefreshLog {
  error_message: string | null
  id: Generated<string>
  is_concurrent: Generated<boolean | null>
  metadata: Generated<Json | null>
  refresh_duration_ms: number | null
  refresh_end: Timestamp | null
  refresh_start: Generated<Timestamp>
  rows_affected: number | null
  status: string
  triggered_by: Generated<string | null>
  view_name: string
}

export interface MemoryEmbeddings {
  content: string
  created_at: Generated<Timestamp>
  /**
   * Ollama nomic-embed-text 768-dimension vector
   */
  embedding: string
  id: Generated<string>
  /**
   * Enum: episodic (conversations), semantic (facts)
   */
  memory_type: Generated<MemoryType>
  /**
   * Flexible JSON metadata for filtering
   */
  metadata: Generated<Json>
  /**
   * Conversation session identifier
   */
  session_id: string
  updated_at: Generated<Timestamp>
  /**
   * FK to auth.users (memory owner)
   */
  user_id: string | null
}

export interface MineBlocks {
  active: Generated<boolean>
  /**
   * Unique block identifier code
   */
  code: string
  created_at: Generated<Timestamp>
  deleted_at: Timestamp | null
  id: Generated<string>
  name: string
  site_id: string | null
  updated_at: Timestamp | null
}

export interface ModbusConnections {
  created_at: Generated<Timestamp>
  department_id: string
  equipment_id: string
  host: string
  id: Generated<string>
  last_connected: Timestamp | null
  port: Generated<number>
  status: Generated<string>
  unit_id: Generated<number>
  updated_at: Generated<Timestamp>
}

export interface ModbusTelemetry {
  created_at: Generated<Timestamp>
  department_id: string
  equipment_id: string
  id: Generated<string>
  registers: Json
  status: Generated<string>
  timestamp: Generated<Timestamp>
}

export interface NetHttpRequestQueue {
  body: Buffer | null
  headers: Json | null
  id: Generated<Int8>
  method: string
  timeout_milliseconds: number
  url: string
}

export interface NetHttpResponse {
  content: string | null
  content_type: string | null
  created: Generated<Timestamp>
  error_msg: string | null
  headers: Json | null
  id: Int8 | null
  status_code: number | null
  timed_out: boolean | null
}

export interface OperationalDelays {
  affected_machine_id: string | null
  /**
   * Roll-up bucket for SMR delay reporting
   */
  category_bucket: string | null
  created_at: Generated<Timestamp>
  created_by: string | null
  delay_category_id: string | null
  delay_date: Timestamp
  /**
   * Duration in minutes (must be > 0)
   */
  delay_minutes: number
  /**
   * Categorization of delay cause
   */
  delay_type: string
  department_id: string
  description: string
  id: Generated<string>
  impact_description: string
  recovery_action: string | null
  shift_type: string
  /**
   * Active, recovered, or extended
   */
  status: Generated<string>
  updated_at: Generated<Timestamp>
}

export interface OperationalDelaysArchive {
  affected_machine_id: string | null
  category_bucket: string | null
  created_at: Generated<Timestamp>
  created_by: string | null
  delay_category_id: string | null
  delay_date: Timestamp
  /**
   * Duration in minutes (must be > 0)
   */
  delay_minutes: number
  /**
   * Categorization of delay cause
   */
  delay_type: string
  department_id: string
  description: string
  id: Generated<string>
  impact_description: string
  recovery_action: string | null
  shift_type: string
  /**
   * Active, recovered, or extended
   */
  status: Generated<string>
  updated_at: Generated<Timestamp>
}

export interface OperatorLogs {
  created_at: Generated<Timestamp>
  department_id: string
  id: Generated<string>
  message: string
  operator_name: string
  updated_at: Generated<Timestamp>
}

export interface Operators {
  active: Generated<boolean>
  created_at: Generated<Timestamp>
  /**
   * Soft delete timestamp
   */
  deleted_at: Timestamp | null
  /**
   * Unique operator identifier code
   */
  employee_code: string
  full_name: string
  id: Generated<string>
  role: Generated<string | null>
  updated_at: Timestamp | null
}

export interface Personnel {
  area: string | null
  created_at: Generated<Timestamp | null>
  department_id: string | null
  emp_code: string
  first_name: string
  id: Generated<string>
  id_number: string
  induction_expiry: Timestamp | null
  job_title: string | null
  medical_expiry: Timestamp | null
  status: Generated<string | null>
  surname: string
  updated_at: Generated<Timestamp | null>
}

export interface ProductionLogs {
  /**
   * Coal production in metric tonnes
   */
  coal_tonnes: Generated<Numeric>
  created_at: Generated<Timestamp>
  created_by: string | null
  daily_log_id: string
  department_id: string
  id: Generated<string>
  log_date: Timestamp
  updated_at: Timestamp | null
  updated_by: string | null
  /**
   * Waste/overburden in metric tonnes
   */
  waste_tonnes: Generated<Numeric>
}

export interface RealtimeMessages {
  binary_payload: Buffer | null
  event: string | null
  extension: string
  id: Generated<string>
  inserted_at: Generated<Timestamp>
  payload: Json | null
  private: Generated<boolean | null>
  topic: string
  updated_at: Generated<Timestamp>
}

export interface RealtimeSchemaMigrations {
  inserted_at: Timestamp | null
  version: Int8
}

export interface RealtimeSubscription {
  action_filter: Generated<string | null>
  claims: Json
  claims_role: Generated<string>
  created_at: Generated<Timestamp>
  entity: string
  filters: Generated<string[]>
  id: Generated<Int8>
  selected_columns: string[] | null
  subscription_id: string
}

export interface ReportTemplates {
  auto_generate: Generated<boolean>
  /**
   * JSON configuration for report generation
   */
  config: Generated<Json | null>
  created_at: Generated<Timestamp>
  deleted_at: Timestamp | null
  description: string | null
  id: Generated<string>
  name: string
  /**
   * Type/category of report
   */
  report_type: string
  updated_at: Timestamp | null
}

export interface SafetyIncidentCategories {
  color: Generated<string>
  description: string | null
  icon: string | null
  id: Generated<string>
  name: string
  sort_order: Generated<number>
  updated_at: Timestamp | null
}

export interface SafetyIncidents {
  category_id: string | null
  closed_at: Timestamp | null
  corrective_action: string
  created_at: Generated<Timestamp>
  department_id: string
  description: string
  id: Generated<string>
  idempotency_key: Generated<string | null>
  incident_date: Timestamp
  /**
   * Enum: near-miss, incident, lost-time, equipment-damage
   */
  incident_type: IncidentType
  injured_parties: Generated<number>
  last_synced_at: Generated<Timestamp | null>
  location: string
  reported_by: string | null
  reviewed_by: string | null
  root_cause: string
  severity_id: string | null
  shift_type: string
  /**
   * Workflow status: open, under-investigation, resolved, closed
   */
  status: Generated<string>
  sync_status: Generated<string | null>
  updated_at: Generated<Timestamp>
}

export interface SafetyObservations {
  assigned_to: string | null
  closed_at: Timestamp | null
  corrective_action: string | null
  created_at: Generated<Timestamp>
  department_id: string
  description: string
  id: Generated<string>
  location: string | null
  observation_date: Timestamp
  observation_type: string
  observed_by: string | null
  risk_level: Generated<string>
  status: Generated<string>
  updated_at: Generated<Timestamp>
}

export interface SafetySeverities {
  color: Generated<string>
  id: Generated<string>
  level: string
  sort_order: Generated<number>
  updated_at: Timestamp | null
  /**
   * Numeric weight for severity scoring
   */
  weight: Generated<number>
}

export interface SatelliteAlerts {
  alert_type: string
  confidence_pct: Generated<Numeric>
  created_at: Generated<Timestamp>
  department_id: string
  description: string | null
  detected_at: Generated<Timestamp>
  id: Generated<string>
  location: Json | null
  notes: string | null
  reviewed: Generated<boolean>
  reviewed_by: string | null
  severity: Generated<string>
  source: string
}

export interface ShiftStatus {
  approved_by: string | null
  closed_at: Timestamp | null
  closed_by: string | null
  created_at: Generated<Timestamp>
  department_id: string
  id: Generated<string>
  notes: string | null
  shift_date: Timestamp
  shift_type: ShiftType
  status: Generated<ShiftStatusType>
  updated_at: Generated<Timestamp>
}

export interface Sites {
  active: Generated<boolean>
  created_at: Generated<Timestamp>
  /**
   * Soft delete timestamp
   */
  deleted_at: Timestamp | null
  id: Generated<string>
  name: string
  /**
   * Unique site code (e.g., PIT-01)
   */
  site_code: string
  updated_at: Timestamp | null
}

export interface SlowQueriesSummary {
  calls: Int8 | null
  mean_ms: Numeric | null
  query_preview: string | null
  rows: Int8 | null
  stddev_ms: Numeric | null
  total_ms: Numeric | null
}

export interface StorageBuckets {
  allowed_mime_types: string[] | null
  avif_autodetection: Generated<boolean | null>
  created_at: Generated<Timestamp | null>
  file_size_limit: Int8 | null
  id: string
  name: string
  /**
   * Field is deprecated, use owner_id instead
   */
  owner: string | null
  owner_id: string | null
  public: Generated<boolean | null>
  type: Generated<StorageBuckettype>
  updated_at: Generated<Timestamp | null>
}

export interface StorageBucketsAnalytics {
  created_at: Generated<Timestamp>
  deleted_at: Timestamp | null
  format: Generated<string>
  id: Generated<string>
  name: string
  type: Generated<StorageBuckettype>
  updated_at: Generated<Timestamp>
}

export interface StorageBucketsVectors {
  created_at: Generated<Timestamp>
  id: string
  type: Generated<StorageBuckettype>
  updated_at: Generated<Timestamp>
}

export interface StorageIcebergNamespaces {
  bucket_name: string
  catalog_id: string
  created_at: Generated<Timestamp>
  id: Generated<string>
  metadata: Generated<Json>
  name: string
  updated_at: Generated<Timestamp>
}

export interface StorageIcebergTables {
  bucket_name: string
  catalog_id: string
  created_at: Generated<Timestamp>
  id: Generated<string>
  location: string
  name: string
  namespace_id: string
  remote_table_id: string | null
  shard_id: string | null
  shard_key: string | null
  updated_at: Generated<Timestamp>
}

export interface StorageMigrations {
  executed_at: Generated<Timestamp | null>
  hash: string
  id: number
  name: string
}

export interface StorageObjects {
  bucket_id: string | null
  created_at: Generated<Timestamp | null>
  id: Generated<string>
  last_accessed_at: Generated<Timestamp | null>
  metadata: Json | null
  name: string | null
  /**
   * Field is deprecated, use owner_id instead
   */
  owner: string | null
  owner_id: string | null
  path_tokens: Generated<string[] | null>
  updated_at: Generated<Timestamp | null>
  user_metadata: Json | null
  version: string | null
}

export interface StorageS3MultipartUploads {
  bucket_id: string
  created_at: Generated<Timestamp>
  id: string
  in_progress_size: Generated<Int8>
  key: string
  metadata: Json | null
  owner_id: string | null
  upload_signature: string
  user_metadata: Json | null
  version: string
}

export interface StorageS3MultipartUploadsParts {
  bucket_id: string
  created_at: Generated<Timestamp>
  etag: string
  id: Generated<string>
  key: string
  owner_id: string | null
  part_number: number
  size: Generated<Int8>
  upload_id: string
  version: string
}

export interface StorageVectorIndexes {
  bucket_id: string
  created_at: Generated<Timestamp>
  data_type: string
  dimension: number
  distance_metric: string
  id: Generated<string>
  metadata_configuration: Json | null
  name: string
  updated_at: Generated<Timestamp>
}

export interface SupabaseFunctionsHooks {
  created_at: Generated<Timestamp>
  hook_name: string
  hook_table_id: number
  id: Generated<Int8>
  request_id: Int8 | null
}

export interface SupabaseFunctionsMigrations {
  inserted_at: Generated<Timestamp>
  version: string
}

export interface SupabaseMigrationsSchemaMigrations {
  name: string | null
  statements: string[] | null
  version: string
}

export interface SurveyMeasurements {
  block_id: string | null
  created_at: Generated<Timestamp>
  department_id: string
  id: Generated<string>
  location: string | null
  measurement_value: Numeric | null
  notes: string | null
  survey_date: Timestamp
  survey_type: string
  surveyed_by: string | null
  unit: string | null
  updated_at: Generated<Timestamp>
}

export interface SurveyPlans {
  accuracy_requirement: string | null
  area_size_ha: Numeric | null
  assigned_surveyor: string | null
  block_id: string | null
  completed_date: Timestamp | null
  created_at: Generated<Timestamp>
  department_id: string
  id: Generated<string>
  notes: string | null
  plan_name: string
  planned_date: Timestamp | null
  point_count: number | null
  status: Generated<string>
  survey_type: string
  updated_at: Generated<Timestamp>
}

export interface SyncWatermarks {
  last_processed_id: string
  table_name: string
  updated_at: Generated<Timestamp>
}

export interface Tires {
  created_at: Generated<Timestamp>
  department_id: string
  fleet_id: string | null
  id: Generated<string>
  installed_at: Timestamp | null
  machine_name: string | null
  notes: string | null
  position: string | null
  pressure_psi: Numeric | null
  replaced_at: Timestamp | null
  size: string | null
  status: Generated<string>
  tread_depth_mm: Numeric | null
  updated_at: Generated<Timestamp>
}

export interface TrainingArchivedDocuments {
  archived_at: Generated<Timestamp>
  archived_by: string | null
  department_id: string
  document_name: string
  document_type: string
  employee_name: string | null
  file_size_bytes: number | null
  file_url: string | null
  id: Generated<string>
  notes: string | null
}

export interface TrainingCourses {
  active: Generated<boolean>
  category: Generated<string>
  completion_rate: Generated<Numeric>
  created_at: Generated<Timestamp>
  created_by: string | null
  department_id: string
  description: string | null
  duration_minutes: Generated<number>
  enrolled_count: Generated<number>
  id: Generated<string>
  lessons: Generated<number>
  level: Generated<string>
  title: string
  updated_at: Generated<Timestamp>
}

export interface TrainingInstructors {
  active: Generated<boolean>
  certifications: string[] | null
  created_at: Generated<Timestamp>
  current_sessions: Generated<number>
  department_id: string
  employee_id: string | null
  id: Generated<string>
  instructor_name: string
  max_concurrent_sessions: Generated<number>
  rating: Numeric | null
  specialization: string | null
  updated_at: Generated<Timestamp>
}

export interface TrainingSchedules {
  capacity: Generated<number>
  course_id: string | null
  course_name: string
  created_at: Generated<Timestamp>
  created_by: string | null
  department_id: string
  end_time: string | null
  filled: Generated<number>
  id: Generated<string>
  instructor: string | null
  location: string | null
  session_date: Timestamp
  session_type: Generated<string>
  start_time: string | null
  status: Generated<string>
  updated_at: Generated<Timestamp>
}

export interface TrainingTrainees {
  avg_score: Numeric | null
  courses_completed: Generated<number>
  courses_in_progress: Generated<number>
  created_at: Generated<Timestamp>
  department_id: string
  employee_id: string | null
  employee_name: string
  enrolled_date: Timestamp
  id: Generated<string>
  last_activity_date: Timestamp | null
  notes: string | null
  role: string | null
  status: Generated<string>
  total_hours_logged: Generated<Numeric>
  updated_at: Generated<Timestamp>
}

export interface VaultDecryptedSecrets {
  created_at: Timestamp | null
  decrypted_secret: string | null
  description: string | null
  id: string | null
  key_id: string | null
  name: string | null
  nonce: Buffer | null
  secret: string | null
  updated_at: Timestamp | null
}

export interface VaultSecrets {
  created_at: Generated<Timestamp>
  description: Generated<string>
  id: Generated<string>
  key_id: string | null
  name: string | null
  nonce: Generated<Buffer | null>
  secret: string
  updated_at: Generated<Timestamp>
}

export interface VectorSearchCache {
  access_count: Generated<number | null>
  cache_key: string
  created_at: Generated<Timestamp>
  last_accessed_at: Generated<Timestamp>
  memory_type: string | null
  query_params: Json
  result_data: Json
  ttl_seconds: Generated<number | null>
  user_id: string
}

export interface VectorSearchPerformance {
  cache_hit: Generated<boolean | null>
  created_at: Generated<Timestamp>
  ef_search: number
  execution_time_ms: number
  id: Generated<string>
  match_count: number
  result_count: number
  search_type: string
  user_id: string
}

export interface Visitors {
  check_in_time: Generated<Timestamp | null>
  check_out_time: Timestamp | null
  company: string | null
  created_at: Generated<Timestamp | null>
  department_id: string | null
  first_name: string
  host_id: string | null
  id: Generated<string>
  id_number: string | null
  reason_for_entry: string
  status: Generated<string | null>
  surname: string
  visiting: string | null
}

export interface WebhookDeliveryLogs {
  created_at: Generated<Timestamp>
  delivered_at: Timestamp | null
  error_message: string | null
  event_type: string
  id: Generated<string>
  payload: Json
  response_body: string | null
  response_status: number | null
  /**
   * Number of retry attempts for failed deliveries
   */
  retry_count: Generated<number>
  success: Generated<boolean>
  webhook_endpoint_id: string
}

export interface WebhookEndpoints {
  active: Generated<boolean>
  created_at: Generated<Timestamp>
  deleted_at: Timestamp | null
  department_id: string | null
  description: string | null
  event_types: Generated<string[]>
  id: Generated<string>
  secret: string | null
  /**
   * Reference to the Svix endpoint ID for webhook management
   */
  svix_endpoint_id: string | null
  updated_at: Timestamp | null
  url: string
}

export interface DB {
  '_realtime.extensions': _RealtimeExtensions
  '_realtime.feature_flags': _RealtimeFeatureFlags
  '_realtime.schema_migrations': _RealtimeSchemaMigrations
  '_realtime.tenants': _RealtimeTenants
  access_logs: AccessLogs
  access_logs_archive: AccessLogsArchive
  admin_audit_trail: AdminAuditTrail
  ai_usage_logs: AiUsageLogs
  alarm_escalation_policy: AlarmEscalationPolicy
  alarm_events: AlarmEvents
  audit_logs: AuditLogs
  'audit.activity_logs': AuditActivityLogs
  'auth.audit_log_entries': AuthAuditLogEntries
  'auth.custom_oauth_providers': AuthCustomOauthProviders
  'auth.flow_state': AuthFlowState
  'auth.identities': AuthIdentities
  'auth.instances': AuthInstances
  'auth.mfa_amr_claims': AuthMfaAmrClaims
  'auth.mfa_challenges': AuthMfaChallenges
  'auth.mfa_factors': AuthMfaFactors
  'auth.oauth_authorizations': AuthOauthAuthorizations
  'auth.oauth_client_states': AuthOauthClientStates
  'auth.oauth_clients': AuthOauthClients
  'auth.oauth_consents': AuthOauthConsents
  'auth.one_time_tokens': AuthOneTimeTokens
  'auth.refresh_tokens': AuthRefreshTokens
  'auth.saml_providers': AuthSamlProviders
  'auth.saml_relay_states': AuthSamlRelayStates
  'auth.schema_migrations': AuthSchemaMigrations
  'auth.sessions': AuthSessions
  'auth.sso_domains': AuthSsoDomains
  'auth.sso_providers': AuthSsoProviders
  'auth.users': AuthUsers
  'auth.webauthn_challenges': AuthWebauthnChallenges
  'auth.webauthn_credentials': AuthWebauthnCredentials
  badges: Badges
  blast_designs: BlastDesigns
  breakdowns: Breakdowns
  card_print_history: CardPrintHistory
  certifications: Certifications
  'cron.job': CronJob
  'cron.job_run_details': CronJobRunDetails
  daily_logs: DailyLogs
  daily_logs_legacy: DailyLogsLegacy
  delay_categories: DelayCategories
  departments: Departments
  document_versions: DocumentVersions
  documents: Documents
  dozer_rolls: DozerRolls
  dozer_rolls_archive: DozerRollsArchive
  drill_operations: DrillOperations
  drill_operations_archive: DrillOperationsArchive
  drill_patterns: DrillPatterns
  embedding_cache: EmbeddingCache
  employees: Employees
  engineering_notes: EngineeringNotes
  engineering_notes_archive: EngineeringNotesArchive
  environmental_incidents: EnvironmentalIncidents
  environmental_readings: EnvironmentalReadings
  equipment: Equipment
  excavator_activity: ExcavatorActivity
  excavator_activity_archive: ExcavatorActivityArchive
  excavator_dumper_assignments: ExcavatorDumperAssignments
  excavator_dumper_assignments_archive: ExcavatorDumperAssignmentsArchive
  'extensions.pg_stat_statements': ExtensionsPgStatStatements
  'extensions.pg_stat_statements_info': ExtensionsPgStatStatementsInfo
  fleet: Fleet
  fleet_maintenance_schedule: FleetMaintenanceSchedule
  fuel_logs: FuelLogs
  generated_reports: GeneratedReports
  grade_control_samples: GradeControlSamples
  hourly_loads: HourlyLoads
  hourly_loads_legacy: HourlyLoadsLegacy
  job_safety_analyses: JobSafetyAnalyses
  machine_configurations: MachineConfigurations
  machine_hours: MachineHours
  machine_operations: MachineOperations
  machine_operations_archive: MachineOperationsArchive
  machine_telemetry: MachineTelemetry
  machine_telemetry_archive: MachineTelemetryArchive
  machines: Machines
  materialized_view_refresh_log: MaterializedViewRefreshLog
  memory_embeddings: MemoryEmbeddings
  mine_blocks: MineBlocks
  modbus_connections: ModbusConnections
  modbus_telemetry: ModbusTelemetry
  'net._http_response': NetHttpResponse
  'net.http_request_queue': NetHttpRequestQueue
  operational_delays: OperationalDelays
  operational_delays_archive: OperationalDelaysArchive
  operator_logs: OperatorLogs
  operators: Operators
  personnel: Personnel
  production_logs: ProductionLogs
  'realtime.messages': RealtimeMessages
  'realtime.schema_migrations': RealtimeSchemaMigrations
  'realtime.subscription': RealtimeSubscription
  report_templates: ReportTemplates
  safety_incident_categories: SafetyIncidentCategories
  safety_incidents: SafetyIncidents
  safety_observations: SafetyObservations
  safety_severities: SafetySeverities
  satellite_alerts: SatelliteAlerts
  shift_status: ShiftStatus
  sites: Sites
  slow_queries_summary: SlowQueriesSummary
  'storage.buckets': StorageBuckets
  'storage.buckets_analytics': StorageBucketsAnalytics
  'storage.buckets_vectors': StorageBucketsVectors
  'storage.iceberg_namespaces': StorageIcebergNamespaces
  'storage.iceberg_tables': StorageIcebergTables
  'storage.migrations': StorageMigrations
  'storage.objects': StorageObjects
  'storage.s3_multipart_uploads': StorageS3MultipartUploads
  'storage.s3_multipart_uploads_parts': StorageS3MultipartUploadsParts
  'storage.vector_indexes': StorageVectorIndexes
  'supabase_functions.hooks': SupabaseFunctionsHooks
  'supabase_functions.migrations': SupabaseFunctionsMigrations
  'supabase_migrations.schema_migrations': SupabaseMigrationsSchemaMigrations
  survey_measurements: SurveyMeasurements
  survey_plans: SurveyPlans
  sync_watermarks: SyncWatermarks
  tires: Tires
  training_archived_documents: TrainingArchivedDocuments
  training_courses: TrainingCourses
  training_instructors: TrainingInstructors
  training_schedules: TrainingSchedules
  training_trainees: TrainingTrainees
  'vault.decrypted_secrets': VaultDecryptedSecrets
  'vault.secrets': VaultSecrets
  vector_search_cache: VectorSearchCache
  vector_search_performance: VectorSearchPerformance
  visitors: Visitors
  webhook_delivery_logs: WebhookDeliveryLogs
  webhook_endpoints: WebhookEndpoints
}
