/**
 * generated.ts — AUTO-GENERATED. DO NOT EDIT.
 *
 * Generated by: packages/theme/scripts/generate-tokens.mjs
 * Source:       packages/theme/src/css/variables.css
 *
 * Re-run with: node packages/theme/scripts/generate-tokens.mjs
 * Or via Turbo: pnpm --filter @repo/theme codegen
 *
 * This file provides typed `var(--token)` references for use in:
 * - Framer Motion style props
 * - Canvas/WebGL drawing
 * - Runtime style injection
 *
 * For static Tailwind usage, use the className utilities instead
 * (e.g. `text-[var(--text-heading)]` or `shadow-card`).
 */

export const tokens = {
  primitives: {
    arch0: 'var(--arch0)',
    arch1: 'var(--arch1)',
    arch2: 'var(--arch2)',
    arch3: 'var(--arch3)',
    arch4: 'var(--arch4)',
    arch5: 'var(--arch5)',
    arch6: 'var(--arch6)',
    arch7: 'var(--arch7)',
    arch8: 'var(--arch8)',
    arch9: 'var(--arch9)',
    arch10: 'var(--arch10)',
    arch11: 'var(--arch11)',
    arch12: 'var(--arch12)',
    arch13: 'var(--arch13)',
    arch14: 'var(--arch14)',
    arch15: 'var(--arch15)',
    archBrandBlue: 'var(--arch-brand-blue)',
    archBrandBlueHover: 'var(--arch-brand-blue-hover)',
    archGlassBackdrop: 'var(--arch-glass-backdrop)',
    archGlassBorder: 'var(--arch-glass-border)',
  },
  hsl: {
    background: '240 5% 96%',
    foreground: '240 6% 10%',
    card: '0 0% 100%',
    cardForeground: '240 6% 10%',
    popover: '0 0% 100%',
    popoverForeground: '240 6% 10%',
    primary: '240 6% 10%',
    primaryForeground: '0 0% 100%',
    secondary: '240 5% 91%',
    secondaryForeground: '240 6% 10%',
    muted: '240 5% 91%',
    mutedForeground: '240 3% 44%',
    accent: '240 5% 91%',
    accentForeground: '240 6% 10%',
    destructive: '3 78% 46%',
    destructiveForeground: '0 0% 100%',
    border: '240 6% 87%',
    input: '240 5% 91%',
    ring: '240 6% 10%',
    'chart-1': '240 6% 10%',
    'chart-2': '142 71% 45%',
    'chart-3': '240 5% 45%',
    'chart-4': '3 78% 46%',
    'chart-5': '270 60% 55%',
    tremorBrandFaint: '240 5% 96%',
    tremorBrandMuted: '240 5% 90%',
    tremorBrandSubtle: '240 5% 65%',
    tremorBrandDefault: '240 6% 10%',
    tremorBrandEmphasis: '0 0% 0%',
    tremorBrandInverted: '0 0% 100%',
    tremorBackgroundMuted: '240 5% 96%',
    tremorBackgroundSubtle: '240 5% 92%',
    tremorBackgroundDefault: '0 0% 100%',
    tremorBackgroundEmphasis: '240 6% 10%',
    tremorBorderDefault: '240 6% 87%',
    tremorRingDefault: '240 6% 10%',
    tremorContentSubtle: '240 3% 63%',
    tremorContentDefault: '240 3% 44%',
    tremorContentEmphasis: '240 6% 23%',
    tremorContentStrong: '240 6% 10%',
    tremorContentInverted: '0 0% 100%',
  },
  color: {
    bg: {
      primary: 'var(--bg-primary)',
      secondary: 'var(--bg-secondary)',
      tertiary: 'var(--bg-tertiary)',
    },
    border: {
      subtle: 'var(--border-subtle)',
      default: 'var(--border-default)',
      emphasis: 'var(--border-emphasis)',
    },
    text: {
      muted: 'var(--text-muted)',
      secondary: 'var(--text-secondary)',
      body: 'var(--text-body)',
      primary: 'var(--text-primary)',
      heading: 'var(--text-heading)',
      onGlass: 'var(--text-on-glass)',
      onGlassMuted: 'var(--text-on-glass-muted)',
      onGlassVideo: 'var(--text-on-glass-video)',
      onGlassVideoMuted: 'var(--text-on-glass-video-muted)',
      onDarkGlass: 'var(--text-on-dark-glass)',
      onDarkGlassMuted: 'var(--text-on-dark-glass-muted)',
    },
    accent: {
      red: 'var(--accent-red)',
      charcoal: 'var(--accent-charcoal)',
      blue: 'var(--accent-blue)',
      green: 'var(--accent-green)',
      electricBlue: 'var(--accent-electric-blue)',
      electricBlueHover: 'var(--accent-electric-blue-hover)',
      electricBlueSubtle: 'var(--accent-electric-blue-subtle)',
      electricBlueBorder: 'var(--accent-electric-blue-border)',
      mint: 'var(--accent-mint)',
      mintHover: 'var(--accent-mint-hover)',
      mintSubtle: 'var(--accent-mint-subtle)',
      mintBorder: 'var(--accent-mint-border)',
      amber: 'var(--accent-amber)',
      amberHover: 'var(--accent-amber-hover)',
      amberSubtle: 'var(--accent-amber-subtle)',
      amberBorder: 'var(--accent-amber-border)',
    },
    mac: {
      red: 'var(--mac-red)',
      yellow: 'var(--mac-yellow)',
      green: 'var(--mac-green)',
      menuBarHeight: 'var(--mac-menu-bar-height)',
    },
    glass: {
      surface: 'var(--glass-surface)',
      surfaceHover: 'var(--glass-surface-hover)',
      surfaceStrong: 'var(--glass-surface-strong)',
      border: 'var(--glass-border)',
      borderTop: 'var(--glass-border-top)',
      videoSurface: 'var(--glass-video-surface)',
      videoSurfaceHover: 'var(--glass-video-surface-hover)',
      videoSurfaceStrong: 'var(--glass-video-surface-strong)',
      videoBackdrop: 'var(--glass-video-backdrop)',
      videoBorder: 'var(--glass-video-border)',
      videoBorderBottom: 'var(--glass-video-border-bottom)',
      videoSheen: 'var(--glass-video-sheen)',
      videoShadow: 'var(--glass-video-shadow)',
      videoRadius: 'var(--glass-video-radius)',
      premiumBackdrop: 'var(--glass-premium-backdrop)',
      premiumBorder: 'var(--glass-premium-border)',
      premiumRadius: 'var(--glass-premium-radius)',
    },
    vibrancy: {
      surface: 'var(--vibrancy-surface)',
      border: 'var(--vibrancy-border)',
    },
  },
  shadow: {
    diffusionSm: 'var(--shadow-diffusion-sm)',
    diffusionMd: 'var(--shadow-diffusion-md)',
    diffusionLg: 'var(--shadow-diffusion-lg)',
    diffusionXl: 'var(--shadow-diffusion-xl)',
    glowPrimary: 'var(--shadow-glow-primary)',
    glowBlue: 'var(--shadow-glow-blue)',
    glowElectricBlue: 'var(--shadow-glow-electric-blue)',
    glowMint: 'var(--shadow-glow-mint)',
    glowAmber: 'var(--shadow-glow-amber)',
    sm: 'var(--shadow-sm)',
    md: 'var(--shadow-md)',
    lg: 'var(--shadow-lg)',
  },
  radius: {},
  wave: {
    intensity: '0.2',
    speedMult: '0.5',
    amplScale: '0.4',
    opacity: '0.25',
  },
} as const

export type Tokens = typeof tokens
export type PrimitiveTokens = typeof tokens.primitives
export type HslTokens = typeof tokens.hsl
export type ColorTokens = typeof tokens.color
export type ShadowTokens = typeof tokens.shadow
export type RadiusTokens = typeof tokens.radius
